#!/usr/bin/python
# -*- coding: utf-8 -*-

# (c) 2016, Eduard Angold <https://github.com/eddyhub>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import urllib2
import json
import os.path
import zipfile
import tempfile
import ast

DOCUMENTATION = '''
---
module: gnome_shell_extension
author: "Patrik Nilsson"
version_added: "2.2"
short_description: Manage gnome shell extensions
description:
   - Download and install gnome shell extensions.
options:
  name:
    required: true
    description:
      - The numeric id of the extension to install.
  url:
    required: false
    default: "https://extensions.gnome.org"
    description:
      - The complete URL to the gnome shell extensions website.
  state:
    required: false
    default: "present"
    description:
      - The desired state of the extension.
  gnome_version:
    required: false
    description:
      - The version of gnome to get the correct extension.
  gnome_extension_path:
    required: true
    description:
      - The path where to install the extension.
'''

EXAMPLES = '''
# Download and install Drop Down Terminal
# https://extensions.gnome.org/extension/442/drop-down-terminal/
- gnome_shell_extension:
    name=442
    gnome_extension_path=/home/edi/.local/share/gnome-shell/extensions/
'''


# ===========================================
# Module code.
#

def is_extension_installed(module, gnome_extension_path, extension_uuid):
    return os.path.isfile(os.path.join(
        gnome_extension_path, extension_uuid, "metadata.json")
    )

def is_extensions_enabled(module, extension_uuid):
    return extension_uuid in set(get_enabled_extensions_list(module))

def get_enabled_extensions_list(module):
    enabled_extensions_str = module.run_command(
        ' '.join(['gsettings', 'get', 'org.gnome.shell',
        'enabled-extensions']))[1]
    return ast.literal_eval(enabled_extensions_str)

def set_extensions(module, extension_list):
    module.run_command(' '.join([
        'gsettings', 'set', 'org.gnome.shell', 'enabled-extensions', '"'
        + str(extension_list) + '"']))

def enable_extension(module, extension_uuid):
    tmp_list = get_enabled_extensions_list(module)
    tmp_list.append(str(extension_uuid))
    set_extensions(module, tmp_list)

def disable_extension(module, extension_uuid):
    tmp_set = set(get_enabled_extensions_list(module))
    tmp_set.remove(str(extension_uuid))
    set_extensions(module, list(tmp_set))

def get_extension_info(module, name, url, gnome_version):
    try:
        info = urllib2.urlopen(
            url + '/extension-info/?pk=' + str(name)
            + '&shell_version=' + gnome_version)
        info = json.load(info)
    except Exception, e:
        module.fail_json(
            msg="Failure downloading metadata from %s %s" % (url, e))
    return info

def install_extension(
        module, url, gnome_extension_path, extension_url, extension_uuid):
    tmp_file = tempfile.TemporaryFile()
    download_url = url + extension_url
    try:
        tmp_file.write(urllib2.urlopen(download_url).read())
        zip_file = zipfile.ZipFile(tmp_file)
        dest_dir = os.path.join(gnome_extension_path, extension_uuid)
        if not os.path.isdir(dest_dir):
            os.makedirs(dest_dir)
        zip_file.extractall(dest_dir)
        tmp_file.close()
    except Exception, e:
        module.fail_json(msg="Failure installing the plugin %s" % e)

def get_installed_extension_info(
        module, gnome_extension_path, extension_uuid):
    try:
        info = json.load(
            open(os.path.join(
                gnome_extension_path, extension_uuid, "metadata.json"))
            )
    except Exception, e:
        module.fail_json(
            msg="Failure loading extension on local machine: %s" % e)
    return info

def main():
    module = AnsibleModule(
        argument_spec = dict(
            state = dict(
                default='present', choices=['present', 'absent'], type='str'),
            name  = dict(required=True, type='str'),
            url   = dict(default='https://extensions.gnome.org', type='str'),
            gnome_version = dict(type='str'),
            gnome_extension_path = dict(required=True, type='str'),
        ),
        supports_check_mode=True
    )

    name = module.params['name']
    state = module.params['state']

    if not module.params['gnome_version']:
        gnome_version = module.run_command(
            " ".join(['gnome-shell', '--version']))[1].split()[-1]
    gnome_extension_path = module.params['gnome_extension_path']
    url = module.params['url']
    extension_info = get_extension_info(module, name, url, gnome_version)

    old_value_is_installed = is_extension_installed(
        module, gnome_extension_path, extension_info['uuid'])

    if not old_value_is_installed and not module.check_mode:
        install_extension(
            module, url, gnome_extension_path,
            extension_info['download_url'], extension_info['uuid'])
    new_value_is_installed = is_extension_installed(
        module, gnome_extension_path, extension_info['uuid'])

    old_value_is_enabled = is_extensions_enabled(
        module, extension_info['uuid'])

    if not old_value_is_enabled or state == 'enabled':
        enable_extension(module, extension_info['uuid'])
    else:
        disable_extension(module, extension_info['uuid'])
    new_value_is_enabled = is_extensions_enabled(
        module, extension_info['uuid'])
    module.exit_json(
            changed=old_value_is_installed !=
            new_value_is_installed or old_value_is_enabled !=
            new_value_is_enabled, msg=extension_info
    )

from ansible.module_utils.basic import AnsibleModule
if __name__ == '__main__':
    main()
